### ISSUE TITLE
vite生产环境打包提示错误信息：Sourcemap is likely to be incorrect: a plugin (vite-plugin-antdv-fix) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help

### ISSUE THREAD

**Issue by meiliujun** [moliyu/vite-plugin-antdv-fix#1]
如题打包过程会出现大量的sourcemap提示， 这个插件使用了 vite的transform api转换代码。 一般生产环境打包sourcemap都关闭的 可以拉一个PR 修改一下么？
修复代码：
vite-plugin-antdv-fix/src/index.ts  73 行 return code
改为 
return {
        code,
        map: null // 表示源码视图不作修改
    }

打包过程错误提示：
![image](https://user-images.githubusercontent.com/7381228/194736274-28f1e469-7785-4976-8035-f46f075e8fc0.png)

**Comment by moliyu** [comment]
完全可以

**Comment by moliyu** [comment]
> 如题打包过程会出现大量的sourcemap提示， 这个插件使用了 vite的transform api转换代码。 一般生产环境打包sourcemap都关闭的 可以拉一个PR 修改一下么？ 修复代码： vite-plugin-antdv-fix/src/index.ts 73 行 return code 改为 return { code, map: null // 表示源码视图不作修改 }
> 
> 打包过程错误提示： ![image](https://user-images.githubusercontent.com/7381228/194736274-28f1e469-7785-4976-8035-f46f075e8fc0.png)
欢迎提pr
